INSERT INTO titles (id, slug, kind, title, tagline, synopsis, release_year, duration_minutes, seasons, maturity_rating, genres, languages, cast_members, director, rating, trending_rank, is_original, hls_url) VALUES
('1','teza','movie','Teza','A return that changes everything','Anberber returns to Eritrea after years abroad and confronts memory, family, and a homeland in transition.',2023,128,NULL,'PG-13','{Drama,Homecoming}','{Tigrinya,English}','{Sara Tesfay,Dawit Okbamichael}','Hanna Ghebremedhin',4.8,1,true,''),
('2','asmara-nights','series','Asmara Nights','The city never sleeps','Four friends navigate love, music, and ambition across Asmara art-deco boulevards.',2024,NULL,2,'TV-14','{Drama,Romance}','{Tigrinya}','{Yonas Haile,Mulu Gebre}','Feven Abraha',4.7,2,true,''),
('3','red-sea-heist','movie','Red Sea Heist','One tide. One score.','A retired diver in Massawa is pulled into one last job beneath the Red Sea.',2024,112,NULL,'PG-13','{Action,Thriller}','{Tigrinya,Arabic}','{Kebrom Tesfa,Liya Asmerom}','Robel Kidane',4.6,3,true,''),
('4','debre-damo','movie','Debre Damo','Faith at the cliff edge','A young monk climbs the legendary monastery carrying a secret.',2022,104,NULL,'PG','{Drama,History}','{Tigrinya}','{Tesfay Berhane,Selam Daniel}','Yosief Mesfin',4.5,4,false,''),
('5','hamasien','series','Hamasien','Land of stories','An anthology of highland folktales retold as prestige television.',2023,NULL,1,'TV-PG','{Anthology,Culture}','{Tigrinya,Tigre}','{Ensemble}','Various',4.6,5,true,''),
('6','coffee-ceremony','movie','Coffee Ceremony','Three rounds. One truth.','During jebena buna, three generations of women finally say what was left unsaid.',2023,96,NULL,'PG','{Drama,Family}','{Tigrinya}','{Amina Idris,Rahel Tekle}','Saba Hagos',4.9,6,true,''),
('7','keren-rally','movie','Keren Rally','Dust, speed, glory','A mechanic from Keren builds a rally car from scrap and races the highlands.',2024,108,NULL,'PG','{Sport,Comedy}','{Tigrinya,English}','{Filmon Asfaha}','Dawit Ghebrehiwet',4.4,7,false,''),
('8','dahlak','series','Dahlak','Islands of pearls and secrets','A marine biologist discovers smuggling routes while mapping Dahlak.',2024,NULL,1,'TV-14','{Mystery,Adventure}','{Tigrinya,Arabic,English}','{Nadia Ali,Samuel Girmay}','Meron Estifanos',4.5,8,true,''),
('9','senait','movie','Senait','A song for the diaspora','A singer in Asmara and her brother in exile finish their father song.',2021,118,NULL,'PG-13','{Music,Drama}','{Tigrinya}','{Helen Tsegay}','Eseyas Tsegay',4.7,9,false,''),
('10','filfil','movie','Filfil','The forest remembers','A botanist protecting the Filfil rainforest uncovers a colonial map.',2022,101,NULL,'PG','{Adventure,History}','{Tigrinya,English}','{Ghidey Gebremedhin}','Lidya Tesfamariam',4.3,10,false,''),
('11','opera-asmara','movie','Opera Asmara','Encore for a cinema palace','Projectionists fight to save the iconic Cinema Impero from demolition.',2023,94,NULL,'G','{Documentary,Culture}','{Tigrinya,Italian}','{Real Asmara voices}','Tomas Ghirmay',4.8,NULL,false,''),
('12','nakfa','series','Nakfa','Courage has a name','A limited series following medics, teachers, and engineers rebuilding.',2025,NULL,1,'TV-14','{History,Drama}','{Tigrinya,English}','{Ensemble}','Hanna Ghebremedhin',4.9,NULL,true,'')
ON CONFLICT (id) DO NOTHING;
