import type { Title } from '@segen/types';

export const mockTitles: Title[] = [
  {
    id: '1', slug: 'teza', kind: 'movie', title: 'Teza',
    tagline: 'A return that changes everything',
    synopsis: 'Anberber returns to Eritrea after years abroad and confronts memory, family, and a homeland in transition.',
    year: 2023, durationMinutes: 128, maturityRating: 'PG-13',
    genres: ['Drama', 'Homecoming'], languages: ['Tigrinya', 'English'],
    cast: ['Sara Tesfay', 'Dawit Okbamichael'], director: 'Hanna Ghebremedhin',
    posterGradient: ['#1C1C20', '#E50914'], heroGradient: ['#0A0A0B', '#B20710'],
    rating: 4.8, trendingRank: 1, isOriginal: true,
  },
  {
    id: '2', slug: 'asmara-nights', kind: 'series', title: 'Asmara Nights',
    tagline: 'The city never sleeps',
    synopsis: 'Four friends navigate love, music, and ambition across Asmara art-deco boulevards.',
    year: 2024, seasons: 2, maturityRating: 'TV-14',
    genres: ['Drama', 'Romance'], languages: ['Tigrinya'],
    cast: ['Yonas Haile', 'Mulu Gebre'], director: 'Feven Abraha',
    posterGradient: ['#131316', '#F9F7F1'], heroGradient: ['#0A0A0B', '#1C1C20'],
    rating: 4.7, trendingRank: 2, isOriginal: true,
  },
  {
    id: '3', slug: 'red-sea-heist', kind: 'movie', title: 'Red Sea Heist',
    tagline: 'One tide. One score.',
    synopsis: 'A retired diver in Massawa is pulled into one last job beneath the Red Sea.',
    year: 2024, durationMinutes: 112, maturityRating: 'PG-13',
    genres: ['Action', 'Thriller'], languages: ['Tigrinya', 'Arabic'],
    cast: ['Kebrom Tesfa', 'Liya Asmerom'], director: 'Robel Kidane',
    posterGradient: ['#B20710', '#0A0A0B'], heroGradient: ['#B20710', '#0A0A0B'],
    rating: 4.6, trendingRank: 3, isOriginal: true,
  },
  {
    id: '4', slug: 'debre-damo', kind: 'movie', title: 'Debre Damo',
    tagline: 'Faith at the cliff edge',
    synopsis: 'A young monk climbs the legendary monastery carrying a secret.',
    year: 2022, durationMinutes: 104, maturityRating: 'PG',
    genres: ['Drama', 'History'], languages: ['Tigrinya'],
    cast: ['Tesfay Berhane', 'Selam Daniel'], director: 'Yosief Mesfin',
    posterGradient: ['#0A0A0B', '#F9F7F1'], heroGradient: ['#0A0A0B', '#1C1C20'],
    rating: 4.5, trendingRank: 4,
  },
  {
    id: '5', slug: 'hamasien', kind: 'series', title: 'Hamasien',
    tagline: 'Land of stories',
    synopsis: 'An anthology of highland folktales retold as prestige television.',
    year: 2023, seasons: 1, maturityRating: 'TV-PG',
    genres: ['Anthology', 'Culture'], languages: ['Tigrinya', 'Tigre'],
    cast: ['Ensemble'], director: 'Various',
    posterGradient: ['#1C1C20', '#B20710'], heroGradient: ['#0A0A0B', '#B20710'],
    rating: 4.6, trendingRank: 5, isOriginal: true,
  },
  {
    id: '6', slug: 'coffee-ceremony', kind: 'movie', title: 'Coffee Ceremony',
    tagline: 'Three rounds. One truth.',
    synopsis: 'During jebena buna, three generations of women finally say what was left unsaid.',
    year: 2023, durationMinutes: 96, maturityRating: 'PG',
    genres: ['Drama', 'Family'], languages: ['Tigrinya'],
    cast: ['Amina Idris', 'Rahel Tekle'], director: 'Saba Hagos',
    posterGradient: ['#F9F7F1', '#B20710'], heroGradient: ['#131316', '#B20710'],
    rating: 4.9, trendingRank: 6, isOriginal: true,
  },
];
